#!/bin/bash

## ggrep
alias grep="$(which ggrep &>/dev/null && echo g)"'grep --color=auto'

## ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

## file
alias file='file -h'

## git
alias gdiff='git diff'
alias cached='git diff --cached'
alias commit='git commit'
alias amend='git commit --amend'
alias no-edit='git commit --amend --no-edit'
alias status='git status'
alias checkout='git checkout'
alias stash='git stash'
alias blame='git blame'
alias branch='git branch'
alias tag='git tag'
alias master='git checkout master'
alias develop='git checkout develop'
alias rcont='git rebase --continue'
alias mcont='git merge --continue'
alias force='push force'
alias prune-rebase='prune && git rebase --autostash origin/master'

## use fancy git diff to diff files
alias difff='git diff --no-index'

## ack=rg ^_^
alias ack='rg --sort-files --no-heading'

## yaml/json
alias y2j='python3 -c "import json, yaml, sys; yamlfile = sys.stdin if len(sys.argv) == 1 else open(sys.argv[1]); print(json.dumps(yaml.safe_load(yamlfile.read())))"'
alias j2y='python3 -c "import json, yaml, sys; jsonfile = sys.stdin if len(sys.argv) == 1 else open(sys.argv[1]); print(yaml.dump(json.loads(jsonfile.read()), default_flow_style=False))"'

## ad-hoc
alias pbpaste-join='pbpaste | tr "\n" " "'
alias ccat='pygmentize -g'
alias weather='curl wttr.in/tokyo'
alias soniq='sort | uniq'
alias f.='find . -path ./.git -prune -o -print | grep'
alias f..='find . | grep'
alias histgrep='history | ack'
alias timeat='date -r'
alias pgrepp='pgrep -afli'

## vagrant
alias ub="VAGRANT_CWD=$HOME/work/vms/focal vagrant"
alias centos="VAGRANT_CWD=$HOME/work/vms/centos vagrant"

## cd
alias yak='cd ~/work/dots'

# iTerm2 Pane ID
alias pbpaste-pane='pbpaste | sed "${pane_id}q;d"' # Paste the $pane_id line from clipboard

# dots/bin aliases
alias google-map='google -m'
alias lucky='google -l'
alias github='google -l github'
alias wiki='google -l wikipedia'
alias stackoverflow='google -l stackoverflow'
alias tabelog='INCOG=yes google -l tabelog'
alias soso='shelloverflow'
