#!/bin/bash

## history
shopt -s histappend
export HISTCONTROL=ignoreboth
export HISTSIZE=50000
export HISTFILESIZE=50000

## colored ls/grep
export CLICOLOR=true

## PS1!
PS1='\[\033[1;32m\]\u \[\033[1;34m\]\w\[\033[0m\]$(__git_ps1) \$ '

## PATH

# Java - http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html
export PATH="/usr/local/jre/bin:$PATH"

# Golang
export GOPATH="$HOME/go"
export PATH=$PATH:"$HOME/go/bin"

# iTerm2 set pane_id
pane_id="$(grep -oE "p\d+:" <<<"${ITERM_SESSION_ID:-}" | grep -oE "\d+" | awk "{print \$0 + 1}")"
