#!/bin/bash

## git
gdifff () { git diff --color "$@" | diff-so-fancy; }
prune () {
  local branch_name="$(git rev-parse --abbrev-ref HEAD)"

  local git_action
  if [[ "${branch_name}" =~ ^(master|develop)$ ]]; then
    git_action=pull
  else
    git_action=fetch
  fi
  echo $(tput setaf 6)git $git_action origin --prune$(tput sgr0)
  git $git_action origin --prune
}
push () {
  local branch_name="$(git rev-parse --abbrev-ref HEAD)"
  local cmd
  local THE_answer
  if [[ "${branch_name}" =~ ^(master|develop)$ ]]; then
    echo "Cannot push to master or develop"
    return 1
  else
    if [ "$1" == "force" ]; then
      cmd="git push origin --force-with-lease"
    else
      cmd="git push origin"
    fi
    echo $cmd $(tput setaf 2)$branch_name$(tput sgr0) | sed 's/\(--force-with-lease\)/'$(tput setaf 1)'&'$(tput sgr0)'/'
    printf "[type 42 to continue] "
    read THE_answer
    if [ "${THE_answer}" = "42" ]; then
      $cmd $branch_name
    fi
  fi
}

## tel
tel () {
  local stepsvr=AAAAAAAAAA
  echo "Telepathing..."
  if nc -v -z -G 3 $stepsvr 22 2> /dev/null ; then
    expect ~/AAAAAAAAAA.expect ssh $stepsvr WEICHU PW "$@"
  else
    echo "Connection failed. Check VPN"
  fi
}

## subl
sf. () { echo "$(f. $@)"; subl $(f. $@); }
sack () { echo "$(ack -l $@)"; subl $(ack -l $@); }
